swagger: '2.0'
info:
  title: Example yaml.spec
  description: test [BountyPls](javascript:prompt(document.cookie)) [a](javascript://www.google.com%0Aalert(1)) [notmalicious](javascript:window.onerror=alert;throw%20document.cookie)
  paths:
  /accounts:
    get:
      responses:
        '200':
          description: Sample
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
