swagger: '2.0'
info:
  title: Example yaml.spec
  description: This is an example text </p><script>alert('XSS')</script> <img src=xss onerror=alert(1)> <svg src=xss onerror=alert(1)> <svg/onload=alert(1)><svg> <svgonload=alert(1)><svg> <input autofocus="" onfocus=alert(1)></input> <details open ontoggle="alert()"> <body onpageshow=alert(1)> <img src=x onerror=alert()>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
